package com.unipay.dto;

import com.unipay.models.Business;
import lombok.Data;

import java.util.Set;

/**
 * Represents the currently authenticated user's data within the system.
 * This DTO is typically returned by authentication or session-related endpoints.
 */
@Data
public class CurrentUser extends BaseEntityDto {

    /**
     * The unique username used to identify and log in the user.
     * This is often used for system-level identification or login credentials.
     */
    private String username;

    /**
     * The unique and valid email address associated with the user.
     * It can be used for communication, password recovery, and login.
     */
    private String email;

    /**
     * Contains the user's personal profile information such as:
     * - Full name
     * - Date of birth
     * - Phone number
     * - Address or other user-identifiable metadata
     */
    private UserProfileDto profile;

    /**
     * Stores the user's customizable settings including:
     * - Preferred language
     * - Timezone
     * - Notification preferences
     */
    private UserSettingsDto settings;

    /**
     * A set of roles assigned to the user to support Role-Based Access Control (RBAC).
     * Each role defines a level of permission or access the user has in the system.
     */
    private Set<UserRoleDto> userRoles;

    /**
     * Contains the user's Multi-Factor Authentication (MFA) configuration.
     * Includes settings like MFA enabled status, secret key, and challenge preferences.
     */
    private MFASettingsDto mfaSettings;

    /**
     * A set of active and historical sessions associated with the user.
     * This allows session management, auditability, and the ability to revoke sessions.
     */
    private Set<UserSessionDto> sessions;

    /**
     * Represents the business entity associated with the user (if applicable).
     * This includes KYB verification data, business details, and onboarding status.
     */
    private BusinessDto business;

    /**
     * Contains payout-related configuration for the user.
     * Includes banking or wallet details where the user receives payments.
     */
    private PayoutSettingsDto payoutSettings;

    /**
     * A set of all transactions initiated or received by the user.
     * Each transaction contains payment-related data such as amount, currency, and status.
     */
    private Set<TransactionDto> transactions;

    /**
     * A set of API keys generated by the user for integrating with external systems.
     * API keys are used for authenticating developer-based access to Unipay's platform.
     */
    private Set<ApiKeyDto> apiKeys;

    /**
     * A set of webhooks configured by the user.
     * Webhooks allow real-time push notifications to external systems when events occur (e.g., payment received).
     */
    private Set<WebhookDto> webhooks;
    private Set<BusinessDto> businesses;
}
